''' GRAPH CONSTANTS '''

IMG_NAME = "house_graph.png"

VERTEX_SIZE = 42
VERTEX_FRAME_WIDTH = 4.0
VERTEX_LABEL_SIZE = 1.0

EDGE_WIDTH = 15

MARGIN = 50
RESIZE_VALUE = (600, 600)


''' PYGAME CONSTANTS '''

CAPTION = "ADL"

WIDTH_DISPLAY = 1200
HEIGHT_DISPLAY = 600
MARGIN_DISPLAY = 42
ROOM_FULL_SIZE = 75
ROOM_HALF_SIZE = ROOM_FULL_SIZE/2
ROOM_OFFSET = 24
IMG_SIZE = 500
DEVIATION_FACTOR = 20

OFFSET_LABEL_X_TYPE = 4
OFFSET_LABEL_Y_TYPE = 2
OFFSET_LABEL_X_NAME = 25
OFFSET_LABEL_Y_NAME = 6

OFFSET_VIEW_X = 37
OFFSET_ICON_Y = 20

WHITE_COLOR = (255,255,255)
BLACK_COLOR = (0,0,0)

HELVETICA_FONT_SIZE_TYPE = 20
HELVETICA_FONT_SIZE_NAME = 11
